//REDUX THUNK STEP 1 CREATING FETCH_COLLECTION ALL

const ShopActionTypes={
    FETCH_COLLECTIONS_START:'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS:'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE:'FETCH_COLLECTIONS_SUCCESS'
}
export default ShopActionTypes