//For deleting cartItem "STEP 1" CLEAR_ITEM_FROM_CART made

//STEP 1 FOR REMOVING ITEM FROM THE ARROWS OF LEFT AND RIGHT WITH QUANTITY NUMBER WRITTEN IN CENTER
const CartActionTypes={
    TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    REMOVE_ITEM:'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART:'CLEAR_ITEM_FROM_CART'
}
export default CartActionTypes